version: '3'
services:
  database:
    container_name: postgres_dev
    restart: always
    image: postgres:10
    env_file:
      - database.conf
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    links:
      - database
    depends_on:
      - database
    ports:
      - 80:80
    environment:
       PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
       PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/root/.pgadmin
volumes:
  pgadmin: