version: "3.5"
services:
  database:
    container_name: postgres_docker
    restart: always
    image: postgres:10
    env_file:
      - database.conf
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql
  app:
    container_name: flask
    restart: always
    build: .
    ports:
      - 5000:5000
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      FLASK_ENV: docker
      FLASK_APP: app.py
    depends_on:
      - database